import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type Language = 'en' | 'ig' | 'yo';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.findServices': 'Find Services',
    'nav.rentGear': 'Rent Gear',
    'nav.marketplace': 'Marketplace',
    'nav.myAccount': 'My Account',
    'nav.profile': 'Profile',
    'nav.signIn': 'Sign In',
    'nav.signOut': 'Sign Out',
    'nav.getStarted': 'Get Started',
    'nav.dashboard': 'Dashboard',
    
    // Common
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.loading': 'Loading...',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.submit': 'Submit',
    'common.bookNow': 'Book Now',
    'common.message': 'Message',
    'common.location': 'Location',
    'common.price': 'Price',
    'common.rating': 'Rating',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.update': 'Update',
    'common.back': 'Back',
    'common.close': 'Close',
    'common.saveChanges': 'Save Changes',
    'common.succeed': 'Succeed',
    
    // Hero
    'hero.badge': 'Trusted by 10,000+ African creatives',
    'hero.title1': 'Empowering',
    'hero.title2': 'African',
    'hero.title3': 'Photographers',
    'hero.description': 'Join the largest platform for African photographers. Book services, rent premium gear, and build your creative business with authentic storytelling.',
    'hero.startCreating': 'Start Creating',
    'hero.watchDemo': 'Watch Demo',
    'hero.demoTitle': 'Choose Your Demo',
    'hero.demoDescription': 'Select the demo that matches your role',
    'hero.forPhotographers': 'For Photographers',
    'hero.photographersDesc': 'Learn how to showcase your work, manage bookings, and grow your client base',
    'hero.watchCreativeDemo': 'Watch Creative Demo',
    'hero.forPrintServices': 'For Print Services',
    'hero.printServicesDesc': 'Discover how to connect with photographers and manage print orders',
    'hero.watchPrinterDemo': 'Watch Printer Demo',
    'hero.stats.photographers': 'African Photographers',
    'hero.stats.projects': 'Projects Completed',
    'hero.stats.countries': 'Countries Served',
    'hero.stats.photographersValue': '10K+',
    'hero.stats.projectsValue': '50K+',
    'hero.stats.countriesValue': '45+',
    'hero.tagline': 'Connect with talented African photographers and rent professional gear',
    'hero.findPhotographers': 'Find Photographers',
    'hero.rentEquipment': 'Rent Equipment',
    
    // Services
    'services.title': 'Discover African Photographers',
    'services.subtitle': 'Browse talented photographers across Africa',
    'services.heroDescription': 'Connect with talented photographers across Africa - from Lagos to Cairo, Nairobi to Cape Town',
    'services.photographersAvailable': 'photographers available',
    'services.across': 'Across',
    'services.majorCities': 'major cities',
    'services.searchPlaceholder': 'Search photographers or specialties...',
    'services.categoryLabel': 'Category',
    'services.locationLabel': 'Location',
    'services.addCustomCategory': 'Add Custom Category',
    'services.allCategories': 'All Categories',
    'services.allLocations': 'All Locations',
    'services.verified': 'Verified',
    'services.by': 'by',
    'services.more': 'more',
    'services.languages': 'Languages',
    'services.loadingMore': 'Loading more services...',
    'services.noResultsTitle': 'No photographers found',
    'services.noResultsDesc': 'Try adjusting your search criteria or explore different categories',
    'services.clearFilters': 'Clear Filters',
    'services.sectionBadge': 'Service Marketplace',
    'services.sectionTitle': 'Connect with Creative Professionals',
    'services.sectionDesc': 'Build your network with photographers, video producers, editors, stylists, and more. Our platform makes it easy to find, book, and collaborate with the best talent in the industry.',
    'services.browseServices': 'Browse Services',
    'services.professionals': '5,000+ Professionals',
    
    // Features
    'features.heading': 'Everything You Need to Succeed',
    'features.description': 'From booking services to renting gear, our platform provides all the tools creative professionals need to grow their business.',
    'features.serviceMarketplace': 'Service Marketplace',
    'features.marketplaceDesc': 'Connect with photographers, editors, stylists, and creative professionals worldwide.',
    'features.gearRentalHub': 'Gear Rental Hub',
    'features.gearDesc': 'Rent premium cameras, lenses, and equipment from verified owners in your area.',
    'features.securePayments': 'Secure Payments',
    'features.paymentsDesc': 'Escrow integration and secure wallets protect both buyers and sellers.',
    'features.smartBooking': 'Smart Booking',
    'features.bookingDesc': 'AI-powered scheduling assistant manages availability and prevents conflicts.',
    'features.messaging': 'In-App Messaging',
    'features.messagingDesc': 'Real-time communication between vendors and clients for seamless collaboration.',
    'features.analytics': 'Analytics Dashboard',
    'features.analyticsDesc': 'Track bookings, income, and performance with detailed analytics and insights.',
    'features.trustAndSafety': 'Trust & Safety',
    'features.trustDesc': 'KYC verification, ratings, reviews, and dispute resolution for peace of mind.',
    'features.flexiblePricing': 'Flexible Pricing',
    'features.pricingDesc': 'Multiple revenue streams and transparent pricing for sustainable growth.',
    
    // Marketplace
    'marketplace.heroTitle': 'Creative',
    'marketplace.heroTitleHighlight': 'Marketplace',
    'marketplace.heroDescription': 'Discover trending services, featured gear, and top-rated professionals across Nigeria',
    'marketplace.exploreServices': 'Explore Services',
    'marketplace.browseGear': 'Browse Gear',
    'marketplace.joinPlatform': 'Join Nigeria\'s Leading',
    'marketplace.photographyPlatform': 'Photography Platform',
    'marketplace.vendorDescription': 'Become a verified vendor and connect with thousands of clients looking for professional photography services.',
    'marketplace.earnedByVendors': 'Earned by our vendors',
    'marketplace.startVendorJourney': 'Start Your Vendor Journey',
    'marketplace.joinPhotographers': 'Join over 450+ photographers already earning on our platform',
    'marketplace.featured': 'Featured',
    'marketplace.topServices': 'Top Services',
    'marketplace.popularGear': 'Popular Gear',
    'marketplace.topVendors': 'Top Vendors',
    'marketplace.trendingThisWeek': 'Trending This Week',
    'marketplace.trendingDesc': 'Portrait photography sessions are up 40%',
    'marketplace.exploreTrend': 'Explore Trend',
    'marketplace.newGearArrivals': 'New Gear Arrivals',
    'marketplace.newGearDesc': 'Latest Canon and Sony cameras now available',
    'marketplace.viewNewGear': 'View New Gear',
    'marketplace.featuredVendors': 'Featured Vendors',
    'marketplace.featuredVendorsDesc': 'Top-rated professionals this month',
    'marketplace.meetExperts': 'Meet the Experts',
    'marketplace.activePhotographers': 'Active Photographers',
    'marketplace.bookingsThisMonth': 'Bookings This Month',
    'marketplace.satisfactionRate': 'Satisfaction Rate',
    'marketplace.totalEarned': 'Total Earned',
    'marketplace.featuredCollections': 'Featured Collections',
    'marketplace.browseCollection': 'Browse Collection',
    'marketplace.topServicesMonth': 'Top Services This Month',
    'marketplace.viewAll': 'View All',
    'marketplace.topRated': 'Top Rated',
    'marketplace.viewProfile': 'View Profile',
    'marketplace.popularGearRentals': 'Popular Gear Rentals',
    'marketplace.viewDetails': 'View Details',
    'marketplace.topRatedVendors': 'Top Rated Vendors',
    'marketplace.viewStudio': 'View Studio',
    'marketplace.projects': 'projects',
    'marketplace.loadingPhotographers': 'Loading photographers...',
    'marketplace.noPhotographers': 'No photographers available yet. Vendors can add their services from their dashboard.',
    'marketplace.featuresList.featured': 'Get featured in our marketplace',
    'marketplace.featuresList.bookingTools': 'Access to premium booking tools',
    'marketplace.featuresList.securePayment': 'Secure payment processing',
    'marketplace.featuresList.profileManagement': 'Professional profile management',
    'marketplace.featuresList.support': '24/7 customer support',
    'marketplace.featuresList.marketing': 'Marketing and promotion support',
    
    // Gear Section
    'gear.title': 'Rent Premium Gear',
    'gear.subtitle': 'Access professional cameras, lenses, and equipment',
    'gear.heroTitleStart': 'Rent',
    'gear.heroTitleHighlight': 'Premium Gear',
    'gear.searchPlaceholder': 'Search gear...',
    'gear.categoryLabel': 'Category',
    'gear.addCustomCategory': 'Add Custom Category',
    'gear.available': 'Available',
    'gear.dailyLabel': 'Daily:',
    'gear.weeklyLabel': 'Weekly:',
    'gear.checkAvailability': 'Check Availability',
    'gear.loadingMore': 'Loading more gear...',
    'gear.condition.excellent': 'Excellent',
    'gear.condition.veryGood': 'Very Good',
    'gear.condition.good': 'Good',
    'gear.sectionBadge': 'Gear Rental Hub',
    'gear.sectionTitle': 'Access Premium Equipment',
    'gear.sectionDesc': 'Rent professional cameras, lenses, lighting, and accessories from verified owners. Get the equipment you need for your next project without the massive investment.',
    'gear.browseGear': 'Browse Gear',
    'gear.itemsAvailable': '2,000+ Items Available',
    
    // Footer
    'footer.tagline': 'Connecting African creatives with opportunities',
    'footer.description': 'The ultimate platform for photographers and creative professionals. Join thousands of creators building their dream careers.',
    'footer.stayUpdated': 'Stay Updated',
    'footer.emailPlaceholder': 'Enter your email',
    'footer.subscribe': 'Subscribe',
    'footer.globalPlatform': 'Global Platform',
    'footer.platform': 'Platform',
    'footer.findServices': 'Find Services',
    'footer.rentGear': 'Rent Gear',
    'footer.marketplace': 'Marketplace',
    'footer.pricing': 'Pricing',
    'footer.resources': 'Resources',
    'footer.helpCenter': 'Help Center',
    'footer.safetyGuidelines': 'Safety Guidelines',
    'footer.community': 'Community',
    'footer.blog': 'Blog',
    'footer.company': 'Company',
    'footer.aboutUs': 'About Us',
    'footer.careers': 'Careers',
    'footer.pressKit': 'Press Kit',
    'footer.contact': 'Contact',
    'footer.legal': 'Legal',
    'footer.privacyPolicy': 'Privacy Policy',
    'footer.termsOfService': 'Terms of Service',
    'footer.cookiePolicy': 'Cookie Policy',
    'footer.gdpr': 'GDPR',
    'footer.copyright': '© 2025 Agemoo. All rights reserved.',
    'footer.digitalEvolutions': 'A Digital Evolutions Project',
    
    // Dashboard - General
    'dashboard.title': 'Photographer Dashboard',
    'dashboard.welcome': 'Welcome back,',
    'dashboard.overview': 'Overview',
    'dashboard.bookings': 'Bookings',
    'dashboard.calendar': 'Calendar',
    'dashboard.services': 'Services',
    'dashboard.profile': 'Profile',
    'dashboard.settings': 'Settings',
    
    // Dashboard - Overview
    'dashboard.recentBookings': 'Recent Bookings',
    'dashboard.viewAll': 'View All',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.messages': 'Messages',
    'dashboard.profileSettings': 'Profile Settings',
    'dashboard.myGear': 'My Gear',
    'dashboard.stats.totalBookings': 'Total Bookings',
    'dashboard.stats.revenue': 'Revenue (MTD)',
    'dashboard.stats.rating': 'Client Rating',
    'dashboard.stats.views': 'Profile Views',
    'dashboard.manageAvailability': 'Manage Availability',

    // Dashboard - Bookings
    'dashboard.manageBookings': 'Manage Bookings',
    'dashboard.manualBooking': 'Manual Booking',
    'dashboard.newBooking': 'New Manual Booking',
    'dashboard.clientName': 'Client Name',
    'dashboard.clientEmail': 'Client Email',
    'dashboard.clientPhone': 'Client Phone',
    'dashboard.serviceName': 'Service Name',
    'dashboard.bookingDate': 'Booking Date',
    'dashboard.bookingTime': 'Booking Time',
    'dashboard.totalPrice': 'Total Price',
    'dashboard.notes': 'Notes',
    'dashboard.status': 'Status',
    'dashboard.status.pending': 'Pending',
    'dashboard.status.confirmed': 'Confirmed',
    'dashboard.status.completed': 'Completed',
    'dashboard.status.cancelled': 'Cancelled',
    'dashboard.status.all': 'All',
    'dashboard.createBooking': 'Create Booking',
    'dashboard.noBookingsYet': 'No bookings yet',
    'dashboard.viewBookingDetails': 'View booking details',

    // Dashboard - Services
    'dashboard.serviceCatalog': 'Service Catalog',
    'dashboard.addService': 'Add Service',
    'dashboard.newService': 'New Service',
    'dashboard.editService': 'Edit Service',
    'dashboard.duration': 'Duration/Terms',
    'dashboard.description': 'Description',
    'dashboard.updateService': 'Update Service',
    'dashboard.noServicesYet': 'No services yet',
    'dashboard.addFirstService': 'Add your first service to get started',

    // Profile & Settings
    'profile.info': 'Profile Information',
    'profile.edit': 'Edit Profile',
    'profile.accountStatus': 'Account Status',
    'profile.verified': 'Verified Professional',
    'profile.publicProfile': 'Public Profile',
    'profile.firstName': 'First Name',
    'profile.lastName': 'Last Name',
    'profile.fullName': 'Full Name',
    'profile.profession': 'Profession',
    'profile.uploading': 'Uploading...',
    'profile.uploadAvatar': 'Upload Avatar',
    'profile.clickToUpload': 'Click to upload avatar',
    'profile.profileUpdated': 'Profile Updated',
    'profile.profileUpdatedDesc': 'Your profile has been successfully updated.',
    'profile.avatarUploaded': 'Avatar uploaded!',
    'profile.avatarUpdatedDesc': 'Your profile picture has been updated.',
    'profile.uploadFailed': 'Upload failed',
    'profile.uploadFailedDesc': 'Failed to upload avatar. Please try again.',
    
    // Settings
    'settings.account': 'Account Settings',
    'settings.payment': 'Payment Settings',
    'settings.updatePayment': 'Update Payment Methods',
    'settings.paymentMethodsUpdated': 'Payment methods updated successfully.',
    'settings.notificationsUpdated': 'Notification settings updated.',
    'settings.emailNotifications': 'Email Notifications',
    'settings.smsNotifications': 'SMS Notifications',
    'settings.bookingNotifications': 'Booking Notifications',
    'settings.marketingEmails': 'Marketing Emails',
    
    // Common Actions
    'action.save': 'Save',
    'action.update': 'Update',
    'action.cancel': 'Cancel',
    'action.delete': 'Delete',
    'action.copyLink': 'Copy Profile Link',
    'action.linkCopied': 'Link Copied!',
    'action.linkCopiedDesc': 'Profile link copied to clipboard.',
    'action.success': 'Success',
    'action.error': 'Error',
    'action.serviceDeleted': 'Service Deleted',
    'action.bookingDeleted': 'Booking Deleted',
    'action.statusUpdated': 'Status Updated',
    'action.bookingMarkedAs': 'Booking marked as',
    'action.browseServices': 'Browse Services',
    
    // Common Labels
    'label.price': 'Price',
    'label.location': 'Location',
    'label.email': 'Email Address',
    'label.phone': 'Phone Number',
    'label.website': 'Website',
    'label.bio': 'Professional Bio',
    'label.specialties': 'Specialties',
    'label.experience': 'Experience',
    'label.equipment': 'Equipment',
    
    // Bookings Page
    'bookings.myBookings': 'My Bookings',
    'bookings.all': 'All',
    'bookings.upcoming': 'Upcoming',
    'bookings.past': 'Past',
    'bookings.loadingBookings': 'Loading bookings...',
    'bookings.noBookingsFound': 'No bookings found',
    'bookings.noBookingsYet': "You don't have any bookings yet. Start by browsing services!",
    'bookings.noFilteredBookings': 'No {filter} bookings found.',
    'bookings.bookingId': 'Booking #',
    
    // Calendar
    'calendar.upcomingBookings': 'Upcoming Bookings',
    'calendar.noUpcomingBookings': 'No upcoming bookings scheduled',
    'calendar.bookingsWillAppear': 'Your confirmed bookings will appear here',
    
    // Messages
    'messages.sendMessage': 'Send Message',
  },
  ig: {
    // Navigation (Igbo)
    'nav.home': 'Ụlọ',
    'nav.findServices': 'Chọta Ọrụ',
    'nav.rentGear': 'Gbazite Ngwá',
    'nav.marketplace': 'Ahịa',
    'nav.myAccount': 'Akaụntụ M',
    'nav.profile': 'Profaịlụ',
    'nav.signIn': 'Banye',
    'nav.signOut': 'Pụọ',
    'nav.getStarted': 'Malite',
    'nav.dashboard': 'Dashibọọdụ',
    
    // Common
    'common.search': 'Chọọ',
    'common.filter': 'Họrọ',
    'common.loading': 'Na-ebu...',
    'common.save': 'Chekwaa',
    'common.cancel': 'Kagbuo',
    'common.submit': 'Zipu',
    'common.bookNow': 'Depụta Ugbu a',
    'common.message': 'Ozi',
    'common.location': 'Ebe',
    'common.price': 'Ọnụ ahịa',
    'common.rating': 'Akara',
    'common.edit': 'Dezie',
    'common.delete': 'Hichapụ',
    'common.update': 'Melite',
    'common.back': 'Laghachi',
    'common.close': 'Mechie',
    'common.saveChanges': 'Chekwaa Mgbanwe',
    'common.succeed': 'Meri',
    
    // Hero
    'hero.badge': 'Nakatụ ndị okike Africa 10,000+ na mma',
    'hero.title1': 'Na-arụ Ọrụ',
    'hero.title2': 'Ndị Foto',
    'hero.title3': 'Africa',
    'hero.description': 'Sonye na ihe ọzọ kacha nnukwu maka ndị foto Africa. Depụta ọrụ, gbazite ngwá dị elu, na wuo ụlọ ọrụ ike gị.',
    'hero.startCreating': 'Malite Ike',
    'hero.watchDemo': 'Lelee Demo',
    'hero.demoTitle': 'Họrọ Demo Gị',
    'hero.demoDescription': 'Họrọ demo nke kwekọ na ọrụ gị',
    'hero.forPhotographers': 'Maka Ndị Foto',
    'hero.photographersDesc': 'Mụta ụzọ igosi ọrụ gị, jikwaa ndepụta, na mụba ndị ahịa',
    'hero.watchCreativeDemo': 'Lelee Demo Ike',
    'hero.forPrintServices': 'Maka Ọrụ Iru',
    'hero.printServicesDesc': 'Chọpụta ụzọ ịjikọ na ndị foto na jikwaa ịrụ ọrụ iru',
    'hero.watchPrinterDemo': 'Lelee Demo Iru',
    'hero.stats.photographers': 'Ndị Foto Africa',
    'hero.stats.projects': 'Ọrụ Emepụtachara',
    'hero.stats.countries': 'Mba Azụrụ',
    'hero.stats.photographersValue': '10K+',
    'hero.stats.projectsValue': '50K+',
    'hero.stats.countriesValue': '45+',
    'hero.tagline': 'Jikọọ na ndị foto Africa na gbazite ngwá ọkachamara',
    'hero.findPhotographers': 'Chọta Ndị Foto',
    'hero.rentEquipment': 'Gbazite Ngwá',
    
    // Services
    'services.title': 'Chọta Ndị Foto Africa',
    'services.subtitle': 'Lelee ndị foto nwere nkà n\'Afrika',
    'services.heroDescription': 'Jikọtara ndị na-ese foto bara ọgụgụ isi n’Afrịka - site na Lagos ruo Cairo, Nairobi ruo Cape Town',
    'services.photographersAvailable': 'ndị na-ese foto dị',
    'services.across': 'n’ofe',
    'services.majorCities': 'obodo ukwu',
    'services.searchPlaceholder': 'Chọọ ndị na-ese foto ma ọ bụ ọkachamara...',
    'services.categoryLabel': 'Otu',
    'services.locationLabel': 'Ebe',
    'services.addCustomCategory': 'Tinye Otu Ọhụrụ',
    'services.allCategories': 'Ụdị Niile',
    'services.allLocations': 'Ebe Niile',
    'services.verified': 'E nyeworo nkwenye',
    'services.by': 'site n’aka',
    'services.more': 'ndị ọzọ',
    'services.languages': 'Asụsụ',
    'services.loadingMore': 'Na-ebute ọrụ ndị ọzọ...',
    'services.noResultsTitle': 'Enweghị ndị na-ese foto',
    'services.noResultsDesc': 'Gbalịa gbanwee ihe ịchọrọ ma ọ bụ chọọ otu dị iche',
    'services.clearFilters': 'Hichapụ ncha',
    'services.sectionBadge': 'Ahịa Ọrụ',
    'services.sectionTitle': 'Jikọọ na Ndị Ọkachamara Ike',
    'services.sectionDesc': 'Wuo netwọk gị pụta na ndị foto, ndị na-emepụta vidiyo, ndị dezie, ndị ihe mma, na ọzọ. Ihe ọzọ ọka mma ụzọ ịchọta, ịdepụta, na ịrụkọ ọrụ na ndị kacha elu n\'ọrụ ahụ.',
    'services.browseServices': 'Lelee Ọrụ',
    'services.professionals': '5,000+ Ndị Ọkachamara',
    
    // Features
    'features.heading': 'Ihe Ịchọta Iji Meri',
    'features.description': 'Site na ndepụta ọrụ ruo na gbazite ngwá, ihe ọka ọka mma ngwá ịchọ ka ndị ọkachamara ike wuo ụlọ ọrụ.',
    'features.serviceMarketplace': 'Ahịa Ọrụ',
    'features.marketplaceDesc': 'Jikọọ na ndị foto, ndị dezie, ndị ihe mma, na ndị ọkachamara ike n\'ụwa.',
    'features.gearRentalHub': 'Ụlọ Gbazite Ngwá',
    'features.gearDesc': 'Gbazite kamera dị elu, oghere, na ngwá site na ndị nwere ikike. Ebe a ọ dị.',
    'features.securePayments': 'Ịkwụ Ụgwọ Nke Ike',
    'features.paymentsDesc': 'Escrow na ndị nwere ahịa nke ike na-echebe onye zụrụ na onye rẹ.',
    'features.smartBooking': 'Ndepụta nke Amamihe',
    'features.bookingDesc': 'AI e mere scheduling na-ejikwaa nnweta na na-egbochi njehie.',
    'features.messaging': 'Ozi N\'Ime Ihe',
    'features.messagingDesc': 'Okwu na-adị n\'oge n\'etiti ndị rẹ na ndị zụrụ.',
    'features.analytics': 'Dashibọọdụ Nyocha',
    'features.analyticsDesc': 'Tụlee ndepụta, ego, na arụmọka na ozi ziri ezi.',
    'features.trustAndSafety': 'Tụkwasị na Nchekwa',
    'features.trustDesc': 'KYC akara, akara ihe, nyocha, na mgbazi maka obi iru ala.',
    'features.flexiblePricing': 'Ọnụ Ahịa Nke Yiri',
    'features.pricingDesc': 'Ọtụtụ ụzọ ego na ọnụ ahịa doro anya maka uju karị.',
    
    // Marketplace
    'marketplace.heroTitle': 'Ahịa',
    'marketplace.heroTitleHighlight': 'Ike',
    'marketplace.heroDescription': 'Chọpụta ọrụ na-ewu ewu, ngwá pụrụ iche, na ndị ọkachamara kacha mma n\'ofe Naịjirịa',
    'marketplace.exploreServices': 'Lelee Ọrụ',
    'marketplace.browseGear': 'Lelee Ngwá',
    'marketplace.joinPlatform': 'Sonye na Naịjirịa',
    'marketplace.photographyPlatform': 'Ụlọ Ọrụ Foto Nke Kasị Mma',
    'marketplace.vendorDescription': 'Bụrụ onye rere ekwenyela ma jikọọ na ọtụtụ puku ndị ahịa na-achọ ọrụ foto ọkachamara.',
    'marketplace.earnedByVendors': 'Ndị rere nwetara',
    'marketplace.startVendorJourney': 'Malite Njem Onye Rere Gị',
    'marketplace.joinPhotographers': 'Sonye na ndị foto 450+ na-enweta ego n\'elu ụlọ ọrụ anyị',
    'marketplace.featured': 'Pụrụ Iche',
    'marketplace.topServices': 'Ọrụ Kacha Mma',
    'marketplace.popularGear': 'Ngwá A Na-achọ',
    'marketplace.topVendors': 'Ndị Rere Kacha Mma',
    'marketplace.trendingThisWeek': 'Na-ewu Ewu Izu a',
    'marketplace.trendingDesc': 'Nnọkọ foto nke onwe bụ 40% elu',
    'marketplace.exploreTrend': 'Lelee Ewu Ewu',
    'marketplace.newGearArrivals': 'Ngwá Ọhụrụ Bịara',
    'marketplace.newGearDesc': 'Kamera Canon na Sony kachasị ọhụrụ dị ugbu a',
    'marketplace.viewNewGear': 'Lelee Ngwá Ọhụrụ',
    'marketplace.featuredVendors': 'Ndị Rere Pụrụ Iche',
    'marketplace.featuredVendorsDesc': 'Ndị ọkachamara kacha mma ọnwa a',
    'marketplace.meetExperts': 'Zute Ndị Ọkachamara',
    'marketplace.activePhotographers': 'Ndị Foto Na-arụ Ọrụ',
    'marketplace.bookingsThisMonth': 'Ndepụta Ọnwa a',
    'marketplace.satisfactionRate': 'Ọnụ Ọgụgụ Afọ Ojuju',
    'marketplace.totalEarned': 'Ngụkọta E Nwetara',
    'marketplace.featuredCollections': 'Nchịkọta Pụrụ Iche',
    'marketplace.browseCollection': 'Lelee Nchịkọta',
    'marketplace.topServicesMonth': 'Ọrụ Kacha Mma Ọnwa a',
    'marketplace.viewAll': 'Lee Niile',
    'marketplace.topRated': 'Kacha Mma',
    'marketplace.viewProfile': 'Lee Profaịlụ',
    'marketplace.popularGearRentals': 'Ngwá Gbazite A Na-achọ',
    'marketplace.viewDetails': 'Lee Nkọwa',
    'marketplace.topRatedVendors': 'Ndị Rere Kacha Mma',
    'marketplace.viewStudio': 'Lee Ụlọ Ọrụ',
    'marketplace.projects': 'ọrụ',
    'marketplace.loadingPhotographers': 'Na-ebu ndị foto...',
    'marketplace.noPhotographers': 'Enweghị ndị foto dị ugbu a. Ndị rere nwere ike tinye ọrụ ha site na dashibọọdụ ha.',
    'marketplace.featuresList.featured': 'Ka e gosipụta gị n\'ahịa anyị',
    'marketplace.featuresList.bookingTools': 'Nweta ngwá ọrụ ndepụta dị elu',
    'marketplace.featuresList.securePayment': 'Nhazi ịkwụ ụgwọ nke nchekwa',
    'marketplace.featuresList.profileManagement': 'Njikwa profaịlụ ọkachamara',
    'marketplace.featuresList.support': 'Nkwado ndị ahịa 24/7',
    'marketplace.featuresList.marketing': 'Nkwado ahịa na nkwalite',
    
    // Gear Section
    'gear.title': 'Gbazite Ngwá Dị Elu',
    'gear.subtitle': 'Nweta kamera ọkachamara, oghere, na ngwá',
    'gear.heroTitleStart': 'Gbazite',
    'gear.heroTitleHighlight': 'Ngwá Dị Elu',
    'gear.searchPlaceholder': 'Chọọ ngwá...',
    'gear.categoryLabel': 'Otu',
    'gear.addCustomCategory': 'Tinye Otu Ọhụrụ',
    'gear.available': 'Dị',
    'gear.dailyLabel': 'Kwa ụbọchị:',
    'gear.weeklyLabel': 'Kwa izu:',
    'gear.checkAvailability': 'Lelee nnweta',
    'gear.loadingMore': 'Na-ebute ngwá ndị ọzọ...',
    'gear.condition.excellent': 'Kacha mma',
    'gear.condition.veryGood': 'Dị ezigbo mma',
    'gear.condition.good': 'Ọma',
    'gear.sectionBadge': 'Ụlọ Gbazite Ngwá',
    'gear.sectionTitle': 'Nweta Ngwá Dị Elu',
    'gear.sectionDesc': 'Gbazite kamera dị elu, oghere, ìhè, na ngwá site na ndị nwere ikike. Nweta ngwá ichọ maka ọrụ gị na ihe na-adịbeghị anya n\'ego.',
    'gear.browseGear': 'Lelee Ngwá',
    'gear.itemsAvailable': 'Ngwá 2,000+ Dị Ebe',
    
    // Footer
    'footer.tagline': 'Na-ejikọta ndị okike Africa na ohere',
    'footer.description': 'Ụlọ ọrụ kachasị mma maka ndị foto na ndị ọkachamara ike. Sonye na ọtụtụ puku ndị okike na-ewu ọrụ nrọ ha.',
    'footer.stayUpdated': 'Nọgide na-emelite',
    'footer.emailPlaceholder': 'Tinye email gị',
    'footer.subscribe': 'Denye aha',
    'footer.globalPlatform': 'Ụlọ Ọrụ Ụwa',
    'footer.platform': 'Ụlọ Ọrụ',
    'footer.findServices': 'Chọta Ọrụ',
    'footer.rentGear': 'Gbazite Ngwá',
    'footer.marketplace': 'Ahịa',
    'footer.pricing': 'Ọnụ Ahịa',
    'footer.resources': 'Akụrụngwa',
    'footer.helpCenter': 'Ebe Enyemaka',
    'footer.safetyGuidelines': 'Nduzi Nchekwa',
    'footer.community': 'Obodo',
    'footer.blog': 'Blog',
    'footer.company': 'Ụlọ Ọrụ',
    'footer.aboutUs': 'Gbasara Anyị',
    'footer.careers': 'Ọrụ',
    'footer.pressKit': 'Ngwa Mgbasa Ozi',
    'footer.contact': 'Kpọtụrụ Anyị',
    'footer.legal': 'Iwu',
    'footer.privacyPolicy': 'Iwu Nzuzo',
    'footer.termsOfService': 'Usoro Ọrụ',
    'footer.cookiePolicy': 'Iwu Cookie',
    'footer.gdpr': 'GDPR',
    'footer.copyright': '© 2025 Agemoo. Ikike niile echekwabara.',
    'footer.digitalEvolutions': 'Ọrụ Digital Evolutions',
    
    // Dashboard - General
    'dashboard.title': 'Dashibọọdụ Onye Foto',
    'dashboard.welcome': 'Nnọọ,',
    'dashboard.overview': 'Nchịkọta',
    'dashboard.bookings': 'Ndepụta',
    'dashboard.calendar': 'Kalenda',
    'dashboard.services': 'Ọrụ',
    'dashboard.profile': 'Profaịlụ',
    'dashboard.settings': 'Ntọala',
    
    // Dashboard - Overview
    'dashboard.recentBookings': 'Ndepụta Na-adịbeghị Anya',
    'dashboard.viewAll': 'Lee Niile',
    'dashboard.quickActions': 'Omume Ngwa Ngwa',
    'dashboard.messages': 'Ozi',
    'dashboard.profileSettings': 'Ntọala Profaịlụ',
    'dashboard.myGear': 'Ngwá M',
    'dashboard.stats.totalBookings': 'Ngụkọta Ndepụta',
    'dashboard.stats.revenue': 'Ego Natara (Ọnwa a)',
    'dashboard.stats.rating': 'Akara Ndị Ahịa',
    'dashboard.stats.views': 'Nlele Profaịlụ',
    'dashboard.manageAvailability': 'Jikwaa Nnweta',

    // Dashboard - Bookings
    'dashboard.manageBookings': 'Jikwaa Ndepụta',
    'dashboard.manualBooking': 'Ndepụta N\'aka',
    'dashboard.newBooking': 'Ndepụta N\'aka Ọhụrụ',
    'dashboard.clientName': 'Aha Onye Ahịa',
    'dashboard.clientEmail': 'Email Onye Ahịa',
    'dashboard.clientPhone': 'Ekwentị Onye Ahịa',
    'dashboard.serviceName': 'Aha Ọrụ',
    'dashboard.bookingDate': 'Ụbọchị Ndepụta',
    'dashboard.bookingTime': 'Oge Ndepụta',
    'dashboard.totalPrice': 'Ọnụ Ahịa Niile',
    'dashboard.notes': 'Nkọwa',
    'dashboard.status': 'Ọnọdụ',
    'dashboard.status.pending': 'Na-eche',
    'dashboard.status.confirmed': 'Ekwenyela',
    'dashboard.status.completed': 'Emechara',
    'dashboard.status.cancelled': 'Kagbuola',
    'dashboard.status.all': 'Niile',
    'dashboard.createBooking': 'Mepụta Ndepụta',
    'dashboard.noBookingsYet': 'Enweghị ndepụta',
    'dashboard.viewBookingDetails': 'Lee nkọwa ndepụta',

    // Dashboard - Services
    'dashboard.serviceCatalog': 'Katalọgụ Ọrụ',
    'dashboard.addService': 'Tinye Ọrụ',
    'dashboard.newService': 'Ọrụ Ọhụrụ',
    'dashboard.editService': 'Dezie Ọrụ',
    'dashboard.duration': 'Ogologo Oge/Usoro',
    'dashboard.description': 'Nkọwa',
    'dashboard.updateService': 'Melite Ọrụ',
    'dashboard.noServicesYet': 'Enweghị ọrụ',
    'dashboard.addFirstService': 'Tinye ọrụ mbụ gị iji malite',

    // Profile & Settings
    'profile.info': 'Ozi Profaịlụ',
    'profile.edit': 'Dezie Profaịlụ',
    'profile.accountStatus': 'Ọnọdụ Akaụntụ',
    'profile.verified': 'Ọkachamara Ekwenyela',
    'profile.publicProfile': 'Profaịlụ Ọha',
    'profile.firstName': 'Aha Mbụ',
    'profile.lastName': 'Aha Ikpeazụ',
    'profile.fullName': 'Aha Zuru Oke',
    'profile.profession': 'Ọrụ',
    'profile.uploading': 'Na-ebunye...',
    'profile.uploadAvatar': 'Bulite Foto Profaịlụ',
    'profile.clickToUpload': 'Pịa iji bulite foto profaịlụ',
    'profile.profileUpdated': 'Emelitela Profaịlụ',
    'profile.profileUpdatedDesc': 'Emelitela profaịlụ gị nke ọma.',
    'profile.avatarUploaded': 'Ebulitela foto!',
    'profile.avatarUpdatedDesc': 'Emelitela foto profaịlụ gị.',
    'profile.uploadFailed': 'Ebulite adaghị',
    'profile.uploadFailedDesc': 'Ebulite foto profaịlụ adaghị. Biko nwaa ọzọ.',
    
    // Settings
    'settings.account': 'Ntọala Akaụntụ',
    'settings.payment': 'Ntọala Ịkwụ Ụgwọ',
    'settings.updatePayment': 'Melite Ụzọ Ịkwụ Ụgwọ',
    'settings.paymentMethodsUpdated': 'Emelitela ụzọ ịkwụ ụgwọ nke ọma.',
    'settings.notificationsUpdated': 'Emelitela ntọala ọkwa.',
    'settings.emailNotifications': 'Ọkwa Email',
    'settings.smsNotifications': 'Ọkwa SMS',
    'settings.bookingNotifications': 'Ọkwa Ndepụta',
    'settings.marketingEmails': 'Email Ahịa',
    
    // Common Actions
    'action.save': 'Chekwaa',
    'action.update': 'Melite',
    'action.cancel': 'Kagbuo',
    'action.delete': 'Hichapụ',
    'action.copyLink': 'Depụta Njikọ Profaịlụ',
    'action.linkCopied': 'Edepụtala Njikọ!',
    'action.linkCopiedDesc': 'Edepụtala njikọ profaịlụ.',
    'action.success': 'Ihe Ịga Nke Ọma',
    'action.error': 'Njehie',
    'action.serviceDeleted': 'Ehichapụla Ọrụ',
    'action.bookingDeleted': 'Ehichapụla Ndepụta',
    'action.statusUpdated': 'Emelitela Ọnọdụ',
    'action.bookingMarkedAs': 'Akara ndepụta dị ka',
    'action.browseServices': 'Lelee Ọrụ',
    
    // Common Labels
    'label.price': 'Ọnụ Ahịa',
    'label.location': 'Ebe',
    'label.email': 'Adreesị Email',
    'label.phone': 'Nọmba Ekwentị',
    'label.website': 'Webụsaịtị',
    'label.bio': 'Nkọwa Ọkachamara',
    'label.specialties': 'Ọrụ Pụrụ Iche',
    'label.experience': 'Ahụmahụ',
    'label.equipment': 'Ngwá',
    
    // Bookings Page
    'bookings.myBookings': 'Ndepụta M',
    'bookings.all': 'Niile',
    'bookings.upcoming': 'Na-abịa',
    'bookings.past': 'Gara Aga',
    'bookings.loadingBookings': 'Na-ebu ndepụta...',
    'bookings.noBookingsFound': 'Achọtaghị ndepụta',
    'bookings.noBookingsYet': 'Ịnweghị ndepụta. Malite site na ịlelee ọrụ!',
    'bookings.noFilteredBookings': 'Achọtaghị ndepụta {filter}.',
    'bookings.bookingId': 'Ndepụta #',
    
    // Calendar
    'calendar.upcomingBookings': 'Ndepụta Na-abịa',
    'calendar.noUpcomingBookings': 'Enweghị ndepụta na-abịa',
    'calendar.bookingsWillAppear': 'Ndepụta gị ga-apụta ebe a',
    
    // Messages
    'messages.sendMessage': 'Zipu Ozi',
  },
  yo: {
    // Navigation (Yoruba)
    'nav.home': 'Ilé',
    'nav.findServices': 'Wá Iṣẹ́',
    'nav.rentGear': 'Yá Ẹ̀rọ',
    'nav.marketplace': 'Ọjà',
    'nav.myAccount': 'Àkọọ́lẹ̀ Mi',
    'nav.profile': 'Profaili',
    'nav.signIn': 'Wọlé',
    'nav.signOut': 'Jáde',
    'nav.getStarted': 'Bẹ̀rẹ̀',
    'nav.dashboard': 'Dasibodu',
    
    // Common
    'common.search': 'Wá',
    'common.filter': 'Yàn',
    'common.loading': 'Ń ṣíṣẹ́...',
    'common.save': 'Fipamọ́',
    'common.cancel': 'Fagilee',
    'common.submit': 'Fi ránṣẹ́',
    'common.bookNow': 'Ṣètò Báyìí',
    'common.message': 'Ìròyìn',
    'common.location': 'Ìbí',
    'common.price': 'Iye owó',
    'common.rating': 'Ìdíyelé',
    'common.edit': 'Ṣàtúnṣe',
    'common.delete': 'Pajẹ',
    'common.update': 'Ṣe ìmúdájú',
    'common.back': 'Padà',
    'common.close': 'Tì',
    'common.saveChanges': 'Fipamọ́ Àwọn Àyípadà',
    'common.succeed': 'Ní Àìkò',
    
    // Hero
    'hero.badge': 'Ìgbìyanju nípa 10,000+ àwọn aláfarawé Áfríkà',
    'hero.title1': 'Ń mú Agbára',
    'hero.title2': 'Àwọn Olùyàwòrán',
    'hero.title3': 'Áfríkà',
    'hero.description': 'Wá sí pẹlú nìyí ìbílẹ̀ jù lọ fún àwọn olùyàwòrán Áfríkà. Ṣètò iṣẹ́, yá ẹ̀rọ gíga, àti ṣẹ̀dá iṣẹ́ ike ìyalẹnu rẹ.',
    'hero.startCreating': 'Bẹ̀rẹ̀ Ìpilẹ̀',
    'hero.watchDemo': 'Wo Demo',
    'hero.demoTitle': 'Yàn Demo Rẹ',
    'hero.demoDescription': 'Yàn demo tó bá rẹ̀ sí iṣẹ́ rẹ',
    'hero.forPhotographers': 'Fún Àwọn Olùyàwòrán',
    'hero.photographersDesc': 'Kọ́ ọ́ nípa báwo ni ó ṣe ìfihàn ṣíṣẹ rẹ, ṣàkóso ìbéèrè, àti tún oníbàárà',
    'hero.watchCreativeDemo': 'Wo Demo Ìpilẹ̀',
    'hero.forPrintServices': 'Fún Iṣẹ́ Tẹ',
    'hero.printServicesDesc': 'Ṣàwárí báwo ni ó ṣe jọ́pọ̀ pẹ̀lú àwọn olùyàwòrán àti ṣàkóso àwọn òran tẹ',
    'hero.watchPrinterDemo': 'Wo Demo Tẹ',
    'hero.stats.photographers': 'Àwọn Olùyàwòrán Áfríkà',
    'hero.stats.projects': 'Àwọn Ṣíṣẹ Tí Parí',
    'hero.stats.countries': 'Àwọn Orílẹ̀-èdè Tí Ní Ìrànlọ́wọ́',
    'hero.stats.photographersValue': '10K+',
    'hero.stats.projectsValue': '50K+',
    'hero.stats.countriesValue': '45+',
    'hero.tagline': 'Sopọ̀ pẹ̀lú àwọn olùyàwòrán Áfríkà tí ó ní tálẹ́ǹtì àti yá ẹ̀rọ ọjọ́gbọ́n',
    'hero.findPhotographers': 'Wá Olùyàwòrán',
    'hero.rentEquipment': 'Yá Ẹ̀rọ',
    
    // Services (Yoruba)
    'services.title': 'Ṣàwárí Àwọn Olùyàwòrán Áfríkà',
    'services.subtitle': 'Wo àwọn olùyàwòrán tí ó ní tálẹ́ǹtì ní Áfríkà',
    'services.heroDescription': 'Sopọ̀ pẹ̀lú àwọn olùyàwòrán agbára kọjá Áfríkà - láti Lagos sí Cairo, Nairobi sí Cape Town',
    'services.photographersAvailable': 'olùyàwòrán wà lọ́nà',
    'services.across': 'káàkiri',
    'services.majorCities': 'àwọn ìlú ńlá',
    'services.searchPlaceholder': 'Wá olùyàwòrán tàbí ìmọ̀ pàtàkì...',
    'services.categoryLabel': 'Ẹ̀ka',
    'services.locationLabel': 'Ìbí',
    'services.addCustomCategory': 'Ṣàfikún Ẹ̀ka Tó Bá Ẹ Mu',
    'services.allCategories': 'Gbogbo Ẹ̀ka',
    'services.allLocations': 'Gbogbo Ìbí',
    'services.verified': 'Ti jẹ́rìísí',
    'services.by': 'lọ́wọ́',
    'services.more': 'míì',
    'services.languages': 'Àwọn Èdè',
    'services.loadingMore': 'Ń kó àwọn iṣẹ́ míì wá...',
    'services.noResultsTitle': 'Kò rí olùyàwòrán',
    'services.noResultsDesc': 'Ṣe àtúnṣe ìbéèrè rẹ tàbí yàn ẹ̀ka míì',
    'services.clearFilters': 'Pa Àlẹ́mọ́ Dànù',
    'services.sectionBadge': 'Ọjà Iṣẹ́',
    'services.sectionTitle': 'Sopọ̀ pẹ̀lú Àwọn Ọjọ́gbọ́n Ìpilẹ̀',
    'services.sectionDesc': 'Ṣẹ̀dá netwọ́ọ̀kì rẹ pẹ̀lú àwọn olùyàwòrán, olùgbé fíìlímu, olùdezie, olùgbémeji, àti mìíràn. Pẹ̀pẹ́ rẹ ń gbé wádìi láṣọ wáyé láti wá, ṣètò, àti fẹ́tọ́ pẹ̀lú ìjọ nínú ẹ̀ròjà.',
    'services.browseServices': 'Wo Àwọn Iṣẹ́',
    'services.professionals': '5,000+ Àwọn Ọjọ́gbọ́n',
    
    // Features (Yoruba)
    'features.heading': 'Ohun Gbogbo Tí O Nílò Láti Ní Àìkò',
    'features.description': 'Látí ṣètò iṣẹ́ sí yíyá ẹ̀rọ, pẹ̀pẹ́ rẹ ṣèe ìkojú ohun gbogbo tí àwọn ọjọ́gbọ́n ìpilẹ̀ nílò làti tún ìṣẹ́.',
    'features.serviceMarketplace': 'Ọjà Iṣẹ́',
    'features.marketplaceDesc': 'Sopọ̀ pẹ̀lú àwọn olùyàwòrán, olùdezie, olùgbémeji, àti àwọn ọjọ́gbọ́n ìpilẹ̀ ní ìgbàkùn àgbáyé.',
    'features.gearRentalHub': 'Ní Ìárandun Ẹ̀rọ',
    'features.gearDesc': 'Yá kámẹ́rà gíga, lẹ́ẹ̀nsì, àti ẹ̀rọ lọ́wọ́ àwọn olùwe tí wọ́n jẹ́rìísí. Ní ibẹ̀ rẹ.',
    'features.securePayments': 'Ìsanwó Tó Ní Ìro',
    'features.paymentsDesc': 'Ìgbésí àsopọ̀ àti àwọn wálẹ̀ẹ̀ tó ní ìro ń àbò ni olùpè ní ọ̀nà àti olùtà.',
    'features.smartBooking': 'Ìbéèrè Tí Ó Ní Ọwọ́',
    'features.bookingDesc': 'AI-pẹ́ájọ́ ní ìbéèrè tí ó ń àkóso wíwà àti ṣíwájú àìṣòwu.',
    'features.messaging': 'Ìròyìn Ní Ìse Ohun',
    'features.messagingDesc': 'Àrò tí ó wà nípa àkókò dáradára láàrín àwọn ọlọ́ràn àti àwọn onímúdájú.',
    'features.analytics': 'Dasibodu Ìkúkú',
    'features.analyticsDesc': 'Ṣe àbídàn àwọn ìbéèrè, owó, àti ìṣẹ́ pẹ̀lú àlàyé tó kéré àti lónìí.',
    'features.trustAndSafety': 'Tìtọ́ & Ìbálẹ̀',
    'features.trustDesc': 'KYC ìdánilójú, ìdíyelé, àwọn ìdábàìmo, àti ìmúdáṣòrò láti ní àkàlò ọkàn.',
    'features.flexiblePricing': 'Iye Owó Tó Yẹ Ara',
    'features.pricingDesc': 'Ọ̀nà owó púpọ̀ àti iye owó àfoífọ̀í fún ìgbéga tó dúró.',
    
    // Marketplace (Yoruba)
    'marketplace.heroTitle': 'Ọjà',
    'marketplace.heroTitleHighlight': 'Ìpilẹ̀',
    'marketplace.heroDescription': 'Ṣàwárí àwọn iṣẹ́ tó ń gbajúmọ̀, ẹ̀rọ pàtàkì, àti àwọn ọjọ́gbọ́n tó dára jù ní Nàìjíríà',
    'marketplace.exploreServices': 'Ṣàwárí Iṣẹ́',
    'marketplace.browseGear': 'Wo Ẹ̀rọ',
    'marketplace.joinPlatform': 'Darapọ̀ Mọ́ Ti Nàìjíríà',
    'marketplace.photographyPlatform': 'Pẹ̀pẹ́ Fọ́tò Tó Ṣàájú',
    'marketplace.vendorDescription': 'Di alátàkọ́ tí a ti jẹ́rìísí kí o sì sopọ̀ pẹ̀lú ẹgbẹẹgbẹ̀rún àwọn oníbàárà tó ń wá iṣẹ́ fọ́tò ọjọ́gbọ́n.',
    'marketplace.earnedByVendors': 'Àwọn alátàkọ́ ti jẹun',
    'marketplace.startVendorJourney': 'Bẹ̀rẹ̀ Ìrìn-àjò Alátàkọ́ Rẹ',
    'marketplace.joinPhotographers': 'Darapọ̀ mọ́ àwọn olùyàwòrán 450+ tó ti ń jẹun lórí pẹ̀pẹ́ wa',
    'marketplace.featured': 'Àṣàyàn',
    'marketplace.topServices': 'Iṣẹ́ Tó Dára Jù',
    'marketplace.popularGear': 'Ẹ̀rọ Olókìkí',
    'marketplace.topVendors': 'Alátàkọ́ Tó Dára Jù',
    'marketplace.trendingThisWeek': 'Ń Gbajúmọ̀ Ọ̀sẹ̀ Yìí',
    'marketplace.trendingDesc': 'Àkópọ̀ fọ́tò ara ẹni pọ̀ sí 40%',
    'marketplace.exploreTrend': 'Ṣàwárí Ìtẹ̀síwájú',
    'marketplace.newGearArrivals': 'Ẹ̀rọ Tuntun Dé',
    'marketplace.newGearDesc': 'Kámẹ́rà Canon àti Sony tuntun wà báyìí',
    'marketplace.viewNewGear': 'Wo Ẹ̀rọ Tuntun',
    'marketplace.featuredVendors': 'Alátàkọ́ Àṣàyàn',
    'marketplace.featuredVendorsDesc': 'Àwọn ọjọ́gbọ́n tó dára jù oṣù yìí',
    'marketplace.meetExperts': 'Pàdé Àwọn Ọjọ́gbọ́n',
    'marketplace.activePhotographers': 'Àwọn Olùyàwòrán Tó Ń Ṣiṣẹ́',
    'marketplace.bookingsThisMonth': 'Àwọn Ìbéèrè Oṣù Yìí',
    'marketplace.satisfactionRate': 'Ìpín Ìtẹ́lọ́rùn',
    'marketplace.totalEarned': 'Lápapọ̀ Tí A Jẹun',
    'marketplace.featuredCollections': 'Àkójọpọ̀ Àṣàyàn',
    'marketplace.browseCollection': 'Wo Àkójọpọ̀',
    'marketplace.topServicesMonth': 'Iṣẹ́ Tó Dára Jù Oṣù Yìí',
    'marketplace.viewAll': 'Wo Gbogbo',
    'marketplace.topRated': 'Tó Dára Jù',
    'marketplace.viewProfile': 'Wo Profaili',
    'marketplace.popularGearRentals': 'Àwọn Ẹ̀rọ Yíyá Olókìkí',
    'marketplace.viewDetails': 'Wo Àlàyé',
    'marketplace.topRatedVendors': 'Alátàkọ́ Tó Dára Jù',
    'marketplace.viewStudio': 'Wo Ilé-iṣẹ́',
    'marketplace.projects': 'àwọn iṣẹ́',
    'marketplace.loadingPhotographers': 'Ń kó àwọn olùyàwòrán...',
    'marketplace.noPhotographers': 'Kò sí olùyàwòrán lọ́wọ́lọ́wọ́. Alátàkọ́ lè ṣàfikún iṣẹ́ wọn láti dasibodu wọn.',
    'marketplace.featuresList.featured': 'Jẹ́ kí a ṣàfihàn ọ ní ọjà wa',
    'marketplace.featuresList.bookingTools': 'Ìrànlọ́wọ́ sí àwọn irinṣẹ́ ìbéèrè gíga',
    'marketplace.featuresList.securePayment': 'Ìlànà ìsanwó tó ní ààbò',
    'marketplace.featuresList.profileManagement': 'Ìṣàkóso profaili ọjọ́gbọ́n',
    'marketplace.featuresList.support': 'Àtìlẹ́yìn oníbàárà 24/7',
    'marketplace.featuresList.marketing': 'Àtìlẹ́yìn títà àti ìpolówó',
    
    // Gear Section (Yoruba)
    'gear.title': 'Yá Ẹ̀rọ Gíga',
    'gear.subtitle': 'Ní ìrànlọ́wọ́ sí kámẹ́rà ọjọ́gbọ́n, lẹ́ẹ̀nsì àti ẹ̀rọ',
    'gear.heroTitleStart': 'Yá',
    'gear.heroTitleHighlight': 'Ẹ̀rọ Gíga',
    'gear.searchPlaceholder': 'Wá ẹ̀rọ...',
    'gear.categoryLabel': 'Ẹ̀ka',
    'gear.addCustomCategory': 'Ṣàfikún Ẹ̀ka Tó Bá Ẹ Mu',
    'gear.available': 'Wà',
    'gear.dailyLabel': 'Ojoojúmọ́:',
    'gear.weeklyLabel': 'Ọ̀sẹ̀:',
    'gear.checkAvailability': 'Ṣàyẹ̀wò Wiwọlé',
    'gear.loadingMore': 'Ń kó ẹ̀rọ míì wá...',
    'gear.condition.excellent': 'Dára púpọ̀',
    'gear.condition.veryGood': 'Dára gan-an',
    'gear.condition.good': 'Dáa',
    'gear.sectionBadge': 'Ní Ìárandun Ẹ̀rọ',
    'gear.sectionTitle': 'Ní Ìrànlọ́wọ́ Ẹ̀rọ Gíga',
    'gear.sectionDesc': 'Yá kámẹ́rà ọjọ́gbọ́n, lẹ́ẹ̀nsì, ìfárahàn, àti ẹ̀rọ lọ́wọ́ àwọn ọ̀kan tí wọ́n ni ìdépìnrin. Ní ẹ̀rọ tí o nílò fún ṣíṣẹ́ rẹ ní ìbámu n\'àìfi owó tí o ríi.',
    'gear.browseGear': 'Wo Ẹ̀rọ',
    'gear.itemsAvailable': 'Ẹ̀rọ 2,000+ Tó Wà Níbẹ̀',
    
    // Footer (Yoruba)
    'footer.tagline': 'Ń sopọ̀ àwọn aláfarawé Áfríkà pẹ̀lú àwọn àǹfààní',    'footer.description': 'Pẹ̀pẹ́ tó dára jù fún àwọn olùyàwòrán àti àwọn ọjọ́gbọ́n ìpilẹ̀. Darapọ̀ mọ́ ẹgbẹẹgbẹ̀rún àwọn aláfarawé tó ń kọ́ iṣẹ́ àlá wọn.',
    'footer.stayUpdated': 'Jẹ́ Kí O Wà Ní Ìmúdájú',
    'footer.emailPlaceholder': 'Tẹ ímèèlì rẹ sí',
    'footer.subscribe': 'Forúkọsílẹ̀',
    'footer.globalPlatform': 'Pẹ̀pẹ́ Àgbáyé',
    'footer.platform': 'Pẹ̀pẹ́',
    'footer.findServices': 'Wá Iṣẹ́',
    'footer.rentGear': 'Yá Ẹ̀rọ',
    'footer.marketplace': 'Ọjà',
    'footer.pricing': 'Iye Owó',
    'footer.resources': 'Àwọn Ohun Èlò',
    'footer.helpCenter': 'Ilé-iṣẹ́ Ìrànlọ́wọ́',
    'footer.safetyGuidelines': 'Ìlànà Ààbò',
    'footer.community': 'Àwùjọ',
    'footer.blog': 'Blog',
    'footer.company': 'Ilé-iṣẹ́',
    'footer.aboutUs': 'Nípa Wa',
    'footer.careers': 'Àwọn Iṣẹ́',
    'footer.pressKit': 'Àpò Ìròyìn',
    'footer.contact': 'Kàn Sí Wa',
    'footer.legal': 'Òfin',
    'footer.privacyPolicy': 'Ìlànà Ìpamọ́',
    'footer.termsOfService': 'Àwọn Òfin Iṣẹ́',
    'footer.cookiePolicy': 'Ìlànà Cookie',
    'footer.gdpr': 'GDPR',
    'footer.copyright': '© 2025 Agemoo. Gbogbo ẹ̀tọ́ ni a dáàbò bò.',
    'footer.digitalEvolutions': 'Iṣẹ́ Digital Evolutions',    
    // Dashboard - General
    'dashboard.title': 'Dasibodu Oluyaworan',
    'dashboard.welcome': 'E kaabo,',
    'dashboard.overview': 'Akopọ',
    'dashboard.bookings': 'Àwọn Ìbéèrè',
    'dashboard.calendar': 'Kálẹ́ndà',
    'dashboard.services': 'Àwọn Iṣẹ́',
    'dashboard.profile': 'Profaili',
    'dashboard.settings': 'Ètò',
    
    // Dashboard - Overview
    'dashboard.recentBookings': 'Àwọn Ìbéèrè Tuntun',
    'dashboard.viewAll': 'Wo Gbogbo',
    'dashboard.quickActions': 'Àwọn Ìgbésẹ̀ Yára',
    'dashboard.messages': 'Àwọn Ìròyìn',
    'dashboard.profileSettings': 'Ètò Profaili',
    'dashboard.myGear': 'Ẹ̀rọ Mi',
    'dashboard.stats.totalBookings': 'Àpapọ̀ Ìbéèrè',
    'dashboard.stats.revenue': 'Owó Wọlé (Oṣù yìí)',
    'dashboard.stats.rating': 'Ìdíyelé Oníbàárà',
    'dashboard.stats.views': 'Àwọn Ìwò Profaili',
    'dashboard.manageAvailability': 'Ṣàkóso Wíwà',

    // Dashboard - Bookings
    'dashboard.manageBookings': 'Ṣàkóso Ìbéèrè',
    'dashboard.manualBooking': 'Ìbéèrè Tààrà',
    'dashboard.newBooking': 'Ìbéèrè Tààrà Tuntun',
    'dashboard.clientName': 'Orúkọ Oníbàárà',
    'dashboard.clientEmail': 'Ímeèlì Oníbàárà',
    'dashboard.clientPhone': 'Fóònù Oníbàárà',
    'dashboard.serviceName': 'Orúkọ Iṣẹ́',
    'dashboard.bookingDate': 'Ọjọ́ Ìbéèrè',
    'dashboard.bookingTime': 'Àkókò Ìbéèrè',
    'dashboard.totalPrice': 'Iye Owó Lápapọ̀',
    'dashboard.notes': 'Àkọsílẹ̀',
    'dashboard.status': 'Ipò',
    'dashboard.status.pending': 'Ń dúró',
    'dashboard.status.confirmed': 'Ti jẹ́rìísí',
    'dashboard.status.completed': 'Ti parí',
    'dashboard.status.cancelled': 'Ti fagilee',
    'dashboard.status.all': 'Gbogbo',
    'dashboard.createBooking': 'Ṣẹ̀dá Ìbéèrè',
    'dashboard.noBookingsYet': 'Kò sí ìbéèrè',
    'dashboard.viewBookingDetails': 'Wo àlàyé ìbéèrè',

    // Dashboard - Services
    'dashboard.serviceCatalog': 'Katalogi Iṣẹ́',
    'dashboard.addService': 'Ṣàfikún Iṣẹ́',
    'dashboard.newService': 'Iṣẹ́ Tuntun',
    'dashboard.editService': 'Ṣàtúnṣe Iṣẹ́',
    'dashboard.duration': 'Ìgbà/Àwọn Òfin',
    'dashboard.description': 'Àlàyé',
    'dashboard.updateService': 'Ṣe Ìmúdájú Iṣẹ́',
    'dashboard.noServicesYet': 'Kò sí iṣẹ́',
    'dashboard.addFirstService': 'Ṣàfikún iṣẹ́ àkọ́kọ́ rẹ láti bẹ̀rẹ̀',

    // Profile & Settings
    'profile.info': 'Ìròyìn Profaili',
    'profile.edit': 'Ṣàtúnṣe Profaili',
    'profile.accountStatus': 'Ipò Àkọọ́lẹ̀',
    'profile.verified': 'Ọjọ́gbọ́n Ti Jẹ́rìísí',
    'profile.publicProfile': 'Profaili Gbangba',
    'profile.firstName': 'Orúkọ Àkọ́kọ́',
    'profile.lastName': 'Orúkọ Ìdílé',
    'profile.fullName': 'Orúkọ Kíkún',
    'profile.profession': 'Iṣẹ́',
    'profile.uploading': 'Ń gbé sókè...',
    'profile.uploadAvatar': 'Gbé Àwòrán Profaili Sókè',
    'profile.clickToUpload': 'Tẹ̀ láti gbé àwòrán profaili sókè',
    'profile.profileUpdated': 'Profaili Ti Ṣe Ìmúdájú',
    'profile.profileUpdatedDesc': 'Profaili rẹ ti ṣe ìmúdájú láìṣòro.',
    'profile.avatarUploaded': 'Àwòrán ti gòkè!',
    'profile.avatarUpdatedDesc': 'Àwòrán profaili rẹ ti ṣe ìmúdájú.',
    'profile.uploadFailed': 'Gbígbé sókè kùnà',
    'profile.uploadFailedDesc': 'Gbígbé àwòrán profaili sókè kùnà. Jọ̀wọ́ gbìyànjú lẹ́ẹ̀kan si.',
    
    // Settings
    'settings.account': 'Ètò Àkọọ́lẹ̀',
    'settings.payment': 'Ètò Ìsanwó',
    'settings.updatePayment': 'Ṣe Ìmúdájú Àwọn Ọ̀nà Ìsanwó',
    'settings.paymentMethodsUpdated': 'Àwọn ọ̀nà ìsanwó ti ṣe ìmúdájú láìṣòro.',
    'settings.notificationsUpdated': 'Ètò ìfitọ́nilétí ti ṣe ìmúdájú.',
    'settings.emailNotifications': 'Ìfitọ́nilétí Ímeèlì',
    'settings.smsNotifications': 'Ìfitọ́nilétí SMS',
    'settings.bookingNotifications': 'Ìfitọ́nilétí Ìbéèrè',
    'settings.marketingEmails': 'Àwọn Ímeèlì Títà',
    
    // Common Actions
    'action.save': 'Fipamọ́',
    'action.update': 'Ṣe Ìmúdájú',
    'action.cancel': 'Fagilee',
    'action.delete': 'Pajẹ',
    'action.copyLink': 'Ṣe Ẹ̀dà Líǹkì Profaili',
    'action.linkCopied': 'Líǹkì Ti Ṣe Ẹ̀dà!',
    'action.linkCopiedDesc': 'Líǹkì profaili ti ṣe ẹ̀dà sí klipibodu.',
    'action.success': 'Àṣeyọrí',
    'action.error': 'Àṣìṣe',
    'action.serviceDeleted': 'Iṣẹ́ Ti Pajẹ',
    'action.bookingDeleted': 'Ìbéèrè Ti Pajẹ',
    'action.statusUpdated': 'Ipò Ti Ṣe Ìmúdájú',
    'action.bookingMarkedAs': 'Ìbéèrè ti sàmì sí',
    'action.browseServices': 'Wo Àwọn Iṣẹ́',
    
    // Common Labels
    'label.price': 'Iye Owó',
    'label.location': 'Ìbí',
    'label.email': 'Àdírẹ́ẹ̀sì Ímeèlì',
    'label.phone': 'Nọ́mbà Fóònù',
    'label.website': 'Wẹ́ẹ̀bù',
    'label.bio': 'Ìtàn Ọjọ́gbọ́n',
    'label.specialties': 'Àwọn Ìmọ̀ Pàtàkì',
    'label.experience': 'Ìrírí',
    'label.equipment': 'Ẹ̀rọ',
    
    // Bookings Page
    'bookings.myBookings': 'Àwọn Ìbéèrè Mi',
    'bookings.all': 'Gbogbo',
    'bookings.upcoming': 'Ń bọ̀',
    'bookings.past': 'Ti kọjá',
    'bookings.loadingBookings': 'Ń ṣíṣẹ́ ìbéèrè...',
    'bookings.noBookingsFound': 'Kò rí ìbéèrè',
    'bookings.noBookingsYet': 'O kò ní ìbéèrè kankan. Bẹ̀rẹ̀ nípa wíwò àwọn iṣẹ́!',
    'bookings.noFilteredBookings': 'Kò rí ìbéèrè {filter}.',
    'bookings.bookingId': 'Ìbéèrè #',
    
    // Calendar
    'calendar.upcomingBookings': 'Àwọn Ìbéèrè Ń bọ̀',
    'calendar.noUpcomingBookings': 'Kò sí ìbéèrè tí ń bọ̀',
    'calendar.bookingsWillAppear': 'Àwọn ìbéèrè rẹ yóò hàn níbí',
    
    // Messages
    'messages.sendMessage': 'Fi Ìròyìn Ránṣẹ́',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
};
