// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pfoxrypsfrvmegtggpnc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBmb3hyeXBzZnJ2bWVndGdncG5jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5OTk0NzgsImV4cCI6MjA2OTU3NTQ3OH0.6uog6xa30DvhQGLyqmQEOlvrg7GXtMdVyZORsqr_B-w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});